apiVersion: v1
kind: Service
metadata:
  name: feedback
  labels:
    app: feedback
spec:
  type: NodePort
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 30091
  selector:
    app: feedback
    tier: display